Units: m
BallRadius: 0.05
LineWidth: 0.05
MarkWidth: 0.1
FieldLength: 6
FieldWidth: 4
GoalDepth: 0.5
GoalWidth: 1.5 # Distance between inner edges of goal posts.
GoalAreaLength: 0.6
GoalAreaWidth: 2.2
GoalCrossbarHeight: 1.0 # Height to the bottom of the crossbar.
GoalpostDiameter: 0.1 # The crossbar diameter and the goalpost diameter are (supposed to be) equal.
GoalCrossbarDiameter: 0.1
GoalNetHeight: 0.8
PenaltyMarkDistance: 1.80 # Measured from the goal line.
CenterCircleDiameter: 1.20
BorderStripMinWidth: 0.7
