[
    {
        "duration": 300,
        "targets": [
            { "id": "R_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "L_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "R_SHOULDER_ROLL", "position": -0.52, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.52, "gain": 30 },
            { "id": "R_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "R_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_PITCH", "position": -0.352902, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -0.352902, "gain": 80 },
            { "id": "R_KNEE", "position": 0.625498, "gain": 80 },
            { "id": "L_KNEE", "position": 0.625498, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -0.337558, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -0.337558, "gain": 80 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "L_HIP_ROLL", "position": 0.053702, "gain": 40 },
            { "id": "R_ANKLE_ROLL", "position": 0.049099, "gain": 40 },
            { "id": "L_ANKLE_ROLL", "position": -0.056771, "gain": 40 }
        ]
    },
    {
        "duration": 300,
        "targets": [
            { "id": "L_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.52, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "R_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "L_HIP_ROLL", "position": 0.053702, "gain": 40 },
            { "id": "R_ANKLE_ROLL", "position": 0.049099, "gain": 40 },
            { "id": "L_ANKLE_ROLL", "position": -0.056771, "gain": 40 },
            { "id": "R_HIP_PITCH", "position": -0.768712, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -0.912941, "gain": 80 },
            { "id": "R_KNEE", "position": 2.192594, "gain": 80 },
            { "id": "L_KNEE", "position": 2.203334, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.385523, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.258171, "gain": 80 },
            { "id": "R_ELBOW", "position": -0.268129, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -0.420222, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 1.799415, "gain": 80 }
        ]
    },
    {
        "duration": 300,
        "targets": [
            { "id": "L_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.52, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "R_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "R_HIP_PITCH", "position": -0.768712, "gain": 80 },
            { "id": "R_KNEE", "position": 2.192594, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.385523, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -0.948232, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -0.506337, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.599933, "gain": 80 },
            { "id": "L_KNEE", "position": 1.620279, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -0.673582, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.05984, "gain": 80 },
            { "id": "R_ELBOW", "position": -0.137708, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -1.012483, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 1.721163, "gain": 80 }
        ]
    },
    {
        "duration": 100,
        "targets": [
            { "id": "L_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.52, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "R_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "R_HIP_PITCH", "position": -0.768712, "gain": 80 },
            { "id": "R_KNEE", "position": 2.192594, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.385523, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -0.506337, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.599933, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.05984, "gain": 80 },
            { "id": "R_ELBOW", "position": -0.137708, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -1.012483, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 1.721163, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.083255, "gain": 80 },
            { "id": "L_KNEE", "position": 2.211006, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -1.107805, "gain": 80 }
        ]
    },
    {
        "duration": 200,
        "targets": [
            { "id": "L_SHOULDER_PITCH", "position": 1.83, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.52, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.79, "gain": 30 },
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "R_HIP_PITCH", "position": -0.768712, "gain": 80 },
            { "id": "R_KNEE", "position": 2.192594, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.385523, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -0.506337, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.599933, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.05984, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.083255, "gain": 80 },
            { "id": "L_KNEE", "position": 2.211006, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -1.107805, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.408139, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 1.668995, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -0.997139, "gain": 80 },
            { "id": "R_ELBOW", "position": -0.86039, "gain": 80 }
        ]
    },
    {
        "duration": 300,
        "targets": [
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 40 },
            { "id": "R_HIP_PITCH", "position": -0.768712, "gain": 80 },
            { "id": "R_KNEE", "position": 2.192594, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.385523, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -0.506337, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.05984, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.083255, "gain": 80 },
            { "id": "L_KNEE", "position": 2.211006, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -1.107805, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.408139, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 1.997347, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -1.414484, "gain": 80 },
            { "id": "R_ELBOW", "position": -2.195279, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.601467, "gain": 80 },
            { "id": "L_SHOULDER_PITCH", "position": 0.780603, "gain": 80 },
            { "id": "L_SHOULDER_ROLL", "position": -0.178177, "gain": 80 },
            { "id": "L_ELBOW", "position": -2.393211, "gain": 80 }
        ]
    },
    {
        "duration": 300,
        "targets": [
            { "id": "L_HIP_YAW", "position": 0, "gain": 50 },
            { "id": "L_ANKLE_PITCH", "position": -1.083255, "gain": 80 },
            { "id": "L_KNEE", "position": 2.211006, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -1.107805, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.408139, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.601467, "gain": 80 },
            { "id": "R_HIP_ROLL", "position": 0.28539, "gain": 80 },
            { "id": "R_HIP_PITCH", "position": 0.176451, "gain": 80 },
            { "id": "R_KNEE", "position": -0.141161, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -0.05984, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -1.362508, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.639826, "gain": 80 },
            { "id": "R_ELBOW", "position": -1.151917, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -0.754711, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": 0.441511, "gain": 80 },
            { "id": "L_SHOULDER_PITCH", "position": 0.780603, "gain": 80 },
            { "id": "L_SHOULDER_ROLL", "position": -0.175108, "gain": 80 },
            { "id": "L_ELBOW", "position": -2.394745, "gain": 80 }
        ]
    },
    {
        "duration": 500,
        "targets": [
            { "id": "R_ELBOW", "position": -0.363259, "gain": 80 },
            { "id": "R_SHOULDER_ROLL", "position": -0.12716, "gain": 80 },
            { "id": "R_SHOULDER_PITCH", "position": -1.15115, "gain": 80 },
            { "id": "L_SHOULDER_PITCH", "position": -1.086707, "gain": 80 },
            { "id": "L_SHOULDER_ROLL", "position": -0.05236, "gain": 80 },
            { "id": "L_ELBOW", "position": -0.3249, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": -0.088993, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.538958, "gain": 80 },
            { "id": "R_KNEE", "position": -0.072115, "gain": 80 },
            { "id": "R_HIP_PITCH", "position": 0.248566, "gain": 80 },
            { "id": "R_HIP_ROLL", "position": 0.047565, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.072115, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.093596, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.53589, "gain": 80 },
            { "id": "L_KNEE", "position": -0.050634, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": 0.222482, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.061374, "gain": 80 },
            { "id": "L_HIP_YAW", "position": 0.047565, "gain": 80 }
        ]
    }
]