- targets:
    - id: L_SHOULDER_PITCH
      position: 1.83
      gain: 20
    - gain: 20
      position: 1.83
      id: R_SHOULDER_PITCH
    - position: 0.52
      id: L_SHOULDER_ROLL
      gain: 20
    - position: -0.52
      gain: 20
      id: R_SHOULDER_ROLL
    - position: -0.79
      id: L_ELBOW
      gain: 20
    - position: -0.79
      gain: 20
      id: R_ELBOW
    - position: -0
      gain: 20
      id: L_HIP_YAW
    - gain: 20
      id: R_HIP_YAW
      position: -0
    - position: -0.352902
      id: L_HIP_PITCH
      gain: 20
    - gain: 20
      id: R_HIP_PITCH
      position: -0.352902
    - id: L_KNEE
      position: 0.625498
      gain: 20
    - id: R_KNEE
      position: 0.625498
      gain: 20
    - gain: 20
      id: L_ANKLE_PITCH
      position: -0.337558
    - position: -0.337558
      gain: 20
      id: R_ANKLE_PITCH
    - gain: 20
      id: L_HIP_ROLL
      position: 0.053702
    - gain: 20
      id: R_HIP_ROLL
      position: -0.053702
    - id: L_ANKLE_ROLL
      gain: 20
      position: -0.049099
    - gain: 20
      id: R_ANKLE_ROLL
      position: 0.056771
  duration: 200
- duration: 100
  targets:
    - position: -0
      gain: 20
      id: L_HIP_YAW
    - id: R_HIP_YAW
      gain: 20
      position: -0
    - gain: 20
      id: L_HIP_PITCH
      position: -0.352902
    - id: R_HIP_PITCH
      position: -0.352902
      gain: 20
    - position: 0.625498
      gain: 20
      id: L_KNEE
    - gain: 20
      position: 0.625498
      id: R_KNEE
    - position: -0.337558
      gain: 20
      id: L_ANKLE_PITCH
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: L_HIP_ROLL
      position: 0.053702
      gain: 20
    - id: R_HIP_ROLL
      position: -0.053702
      gain: 20
    - id: L_ANKLE_ROLL
      position: -0.049099
      gain: 20
    - id: R_ANKLE_ROLL
      position: 0.056771
      gain: 20
    - position: -0
      gain: 20
      id: L_SHOULDER_ROLL
    - id: R_SHOULDER_ROLL
      position: -0
      gain: 20
    - id: R_SHOULDER_PITCH
      position: -0.9501496
      gain: 20
    - position: -0.9800695
      id: R_ELBOW
      gain: 20
    - position: -0.8649929
      gain: 20
      id: L_ELBOW
    - id: L_SHOULDER_PITCH
      position: -0.8811036
      gain: 20
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 20
    - id: R_HIP_YAW
      position: -0
      gain: 20
    - gain: 20
      id: L_HIP_PITCH
      position: -0.352902
    - id: R_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: L_KNEE
      position: 0.625498
      gain: 20
    - gain: 20
      position: 0.625498
      id: R_KNEE
    - id: L_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - position: -0
      gain: 20
      id: L_SHOULDER_ROLL
    - id: R_SHOULDER_ROLL
      position: -0
      gain: 20
    - position: -0.9501496
      gain: 20
      id: R_SHOULDER_PITCH
    - position: -0.9800695
      gain: 20
      id: R_ELBOW
    - gain: 20
      position: -0.8649929
      id: L_ELBOW
    - id: L_SHOULDER_PITCH
      position: -0.8811036
      gain: 20
    - position: 0.8224145
      gain: 20
      id: R_ANKLE_ROLL
    - position: 0.7303532
      gain: 20
      id: L_ANKLE_ROLL
    - position: -0.9190789
      gain: 20
      id: R_HIP_ROLL
    - position: -0.8822544
      gain: 20
      id: L_HIP_ROLL
  duration: 300