- duration: 200
  targets:
    - id: R_SHOULDER_PITCH
      position: 1.83
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.83
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.52
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.52
      gain: 20
    - id: R_ELBOW
      position: -0.79
      gain: 20
    - id: L_ELBOW
      position: -0.79
      gain: 20
    - id: R_HIP_YAW
      position: 0
      gain: 20
    - id: L_HIP_YAW
      position: 0
      gain: 20
    - id: R_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: L_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: R_KNEE
      position: 0.625498
      gain: 20
    - id: L_KNEE
      position: 0.625498
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: L_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: R_HIP_ROLL
      position: -0.053702
      gain: 20
    - id: L_HIP_ROLL
      position: 0.053702
      gain: 20
    - id: R_ANKLE_ROLL
      position: 0.049099
      gain: 20
    - id: L_ANKLE_ROLL
      position: -0.056771
      gain: 20
- targets:
    - gain: 20
      id: R_HIP_YAW
      position: 0
    - id: L_HIP_YAW
      position: 0
      gain: 20
    - id: R_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: L_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: R_KNEE
      position: 0.625498
      gain: 20
    - id: L_KNEE
      position: 0.625498
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: L_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: R_HIP_ROLL
      position: -0.053702
      gain: 20
    - id: L_HIP_ROLL
      position: 0.053702
      gain: 20
    - id: R_ANKLE_ROLL
      position: 0.049099
      gain: 20
    - id: L_ANKLE_ROLL
      position: -0.056771
      gain: 20
    - id: R_SHOULDER_ROLL
      position: 0
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0
      gain: 20
    - id: L_SHOULDER_PITCH
      position: -0.9501496
      gain: 20
    - id: L_ELBOW
      position: -0.9800695
      gain: 20
    - id: R_ELBOW
      position: -0.8649929
      gain: 20
    - id: R_SHOULDER_PITCH
      position: -0.8811036
      gain: 20
  duration: 100
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 20
    - id: L_HIP_YAW
      position: 0
      gain: 20
    - id: R_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: L_HIP_PITCH
      position: -0.352902
      gain: 20
    - id: R_KNEE
      position: 0.625498
      gain: 20
    - id: L_KNEE
      position: 0.625498
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: L_ANKLE_PITCH
      position: -0.337558
      gain: 20
    - id: R_SHOULDER_ROLL
      position: 0
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0
      gain: 20
    - id: L_SHOULDER_PITCH
      position: -0.9501496
      gain: 20
    - id: L_ELBOW
      position: -0.9800695
      gain: 20
    - id: R_ELBOW
      position: -0.8649929
      gain: 20
    - id: R_SHOULDER_PITCH
      position: -0.8811036
      gain: 20
    - id: L_ANKLE_ROLL
      position: -0.8224145
      gain: 20
    - id: R_ANKLE_ROLL
      position: -0.7303532
      gain: 20
    - id: L_HIP_ROLL
      position: 0.9190789
      gain: 20
    - id: R_HIP_ROLL
      position: 0.8822544
      gain: 20
  duration: 300