- targets:
    - id: L_HIP_YAW
      position: -0.003069
      gain: 40
    - id: R_HIP_ROLL
      position: -0.053702
      gain: 40
    - id: L_HIP_ROLL
      position: 0.055237
      gain: 40
    - id: R_HIP_PITCH
      position: -0.35597
      gain: 40
    - id: L_HIP_PITCH
      position: -0.348299
      gain: 40
    - id: R_KNEE
      position: 0.627551
      gain: 40
    - id: L_KNEE
      position: 0.632154
      gain: 40
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 40
    - id: L_ANKLE_PITCH
      position: -0.336024
      gain: 40
    - id: R_ANKLE_ROLL
      position: 0.042962
      gain: 40
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 40
    - id: R_HIP_YAW
      position: 0.006137
      gain: 40
    - id: L_ELBOW
      position: 0
      gain: 20
    - id: R_ELBOW
      position: 0
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.124091
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.497
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.497147
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.081129
      gain: 20
  duration: 75
- targets:
    - id: L_HIP_YAW
      position: -0.003069
      gain: 40
    - id: R_ANKLE_ROLL
      position: 0.042962
      gain: 40
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 40
    - id: R_HIP_YAW
      position: 0.001534
      gain: 40
    - id: L_HIP_ROLL
      position: -0.076718
      gain: 40
    - id: R_HIP_ROLL
      position: -0.049099
      gain: 40
    - id: L_ANKLE_PITCH
      position: -1.255103
      gain: 40
    - id: R_ANKLE_PITCH
      position: -1.241294
      gain: 40
    - id: L_KNEE
      position: 2.263174
      gain: 40
    - id: R_KNEE
      position: 2.22635
      gain: 40
    - id: L_HIP_PITCH
      position: -0.917545
      gain: 40
    - id: R_HIP_PITCH
      position: -0.911407
      gain: 40
    - id: R_ELBOW
      position: -0.564259
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.587466
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.891477
      gain: 20
    - id: L_ELBOW
      position: -0.659389
      gain: 20
    - position: 0.57826
      id: L_SHOULDER_ROLL
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.834705
      gain: 20
  duration: 1000