[
    {
        "duration": 75,
        "targets": [
            { "id": "L_HIP_YAW", "position": -0.003069, "gain": 80 },
            { "id": "R_HIP_ROLL", "position": -0.053702, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": 0.055237, "gain": 80 },
            { "id": "R_HIP_PITCH", "position": -0.35597, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -0.348299, "gain": 80 },
            { "id": "R_KNEE", "position": 0.627551, "gain": 80 },
            { "id": "L_KNEE", "position": 0.632154, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -0.337558, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -0.336024, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": 0.042962, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.05984, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.006137, "gain": 80 },
            { "id": "L_ELBOW", "position": 0, "gain": 30 },
            { "id": "R_ELBOW", "position": 0, "gain": 30 },
            { "id": "R_SHOULDER_ROLL", "position": -0.124091, "gain": 30 },
            { "id": "L_SHOULDER_PITCH", "position": 1.497, "gain": 30 },
            { "id": "R_SHOULDER_PITCH", "position": 1.497147, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.081129, "gain": 30 }
        ]
    },
    {
        "duration": 1000,
        "targets": [
            { "id": "L_HIP_YAW", "position": -0.003069, "gain": 80 },
            { "id": "R_ANKLE_ROLL", "position": 0.042962, "gain": 80 },
            { "id": "L_ANKLE_ROLL", "position": -0.05984, "gain": 80 },
            { "id": "R_HIP_YAW", "position": 0.001534, "gain": 80 },
            { "id": "L_HIP_ROLL", "position": -0.076718, "gain": 80 },
            { "id": "R_HIP_ROLL", "position": -0.049099, "gain": 80 },
            { "id": "L_ANKLE_PITCH", "position": -1.255103, "gain": 80 },
            { "id": "R_ANKLE_PITCH", "position": -1.241294, "gain": 80 },
            { "id": "L_KNEE", "position": 2.263174, "gain": 80 },
            { "id": "R_KNEE", "position": 2.22635, "gain": 80 },
            { "id": "L_HIP_PITCH", "position": -0.917545, "gain": 80 },
            { "id": "R_HIP_PITCH", "position": -0.911407, "gain": 80 },
            { "id": "R_ELBOW", "position": -0.564259, "gain": 30 },
            { "id": "R_SHOULDER_ROLL", "position": -0.587466, "gain": 30 },
            { "id": "R_SHOULDER_PITCH", "position": 1.891477, "gain": 30 },
            { "id": "L_ELBOW", "position": -0.659389, "gain": 30 },
            { "id": "L_SHOULDER_ROLL", "position": 0.57826, "gain": 30 },
            { "id": "L_SHOULDER_PITCH", "position": 1.834705, "gain": 30 }
        ]
    }
]