- targets:
    - position: -0.003069
      gain: 40
      id: L_HIP_YAW
    - position: -0.053702
      gain: 40
      id: R_HIP_ROLL
    - id: L_HIP_ROLL
      position: 0.055237
      gain: 40
    - id: R_HIP_PITCH
      position: -0.35597
      gain: 40
    - id: L_HIP_PITCH
      position: -0.348299
      gain: 40
    - id: R_KNEE
      position: 0.627551
      gain: 40
    - id: L_KNEE
      position: 0.632154
      gain: 40
    - id: R_ANKLE_PITCH
      position: -0.337558
      gain: 40
    - id: L_ANKLE_PITCH
      position: -0.336024
      gain: 40
    - id: R_ANKLE_ROLL
      position: 0.042962
      gain: 40
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 40
    - id: R_HIP_YAW
      position: 0.006137
      gain: 40
    - id: L_ELBOW
      position: 0
      gain: 20
    - id: R_ELBOW
      position: 0
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.124091
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.497
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.497147
      gain: 20
    - gain: 20
      id: L_SHOULDER_ROLL
      position: 0.081129
  duration: 75
- targets:
    - gain: 50
      id: L_HIP_YAW
      position: -0.003069
    - position: 0.042962
      gain: 50
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 50
    - id: R_HIP_YAW
      position: 0.001534
      gain: 50
    - id: L_HIP_ROLL
      position: -0.076718
      gain: 50
    - id: R_HIP_ROLL
      position: -0.049099
      gain: 50
    - id: L_ANKLE_PITCH
      position: -1.255103
      gain: 50
    - id: R_ANKLE_PITCH
      position: -1.241294
      gain: 50
    - id: L_KNEE
      position: 2.263174
      gain: 50
    - id: R_KNEE
      position: 2.22635
      gain: 50
    - id: L_HIP_PITCH
      position: -0.917545
      gain: 50
    - id: R_HIP_PITCH
      position: -0.911407
      gain: 50
    - id: L_ELBOW
      position: -0.668595
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.642703
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.665926
      gain: 20
    - id: R_ELBOW
      position: -0.562725
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.618153
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.788675
      gain: 20
  duration: 1000
- targets:
    - gain: 50
      id: L_HIP_YAW
      position: -0.003069
    - id: R_ANKLE_ROLL
      position: 0.042962
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 50
    - id: R_HIP_YAW
      position: 0.001534
      gain: 50
    - id: L_HIP_ROLL
      position: -0.076718
      gain: 50
    - id: R_HIP_ROLL
      position: -0.049099
      gain: 50
    - id: L_ANKLE_PITCH
      position: -1.255103
      gain: 50
    - id: R_ANKLE_PITCH
      position: -1.241294
      gain: 50
    - id: L_KNEE
      position: 2.263174
      gain: 50
    - id: R_KNEE
      position: 2.22635
      gain: 50
    - id: L_HIP_PITCH
      position: -0.917545
      gain: 50
    - id: R_HIP_PITCH
      position: -0.911407
      gain: 50
    - id: L_ELBOW
      position: -0.668595
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.642703
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.665926
      gain: 20
    - id: R_ELBOW
      position: -0.562725
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.618153
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.788675
      gain: 20
  duration: 3000
- targets:
    - id: L_HIP_YAW
      position: -0.003069
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.042962
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.05984
      gain: 50
    - id: R_HIP_YAW
      position: 0.001534
      gain: 50
    - id: L_HIP_ROLL
      position: -0.076718
      gain: 50
    - id: R_HIP_ROLL
      position: -0.049099
      gain: 50
    - id: L_ANKLE_PITCH
      position: -1.255103
      gain: 50
    - id: R_ANKLE_PITCH
      position: -1.241294
      gain: 50
    - id: L_KNEE
      position: 2.263174
      gain: 50
    - id: R_KNEE
      position: 2.22635
      gain: 50
    - id: R_SHOULDER_PITCH
      position: 1.598415
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.615293
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.124091
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.182397
      gain: 20
    - id: R_ELBOW
      position: -0.512091
      gain: 20
    - id: L_ELBOW
      position: -0.711557
      gain: 20
    - id: L_HIP_PITCH
      position: -1.215209
      gain: 50
    - id: R_HIP_PITCH
      position: -1.221347
      gain: 50
  duration: 400
- targets:
    - gain: 40
      id: L_HIP_YAW
      position: -0.003
    - id: R_ANKLE_ROLL
      position: 0.043
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.06
      gain: 50
    - id: R_HIP_YAW
      position: 0.006
      gain: 50
    - id: L_HIP_ROLL
      position: 0.055
      gain: 40
    - id: R_HIP_ROLL
      position: -0.054
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.336
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.338
      gain: 50
    - id: L_KNEE
      position: 0.632
      gain: 40
    - id: R_KNEE
      position: 0.628
      gain: 50
    - id: R_SHOULDER_PITCH
      position: 1.497
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.497
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.124
      gain: 20
    - id: R_ELBOW
      position: 0
      gain: 20
    - id: L_ELBOW
      position: 0
      gain: 20
    - id: L_HIP_PITCH
      position: -0.348
      gain: 40
    - id: R_HIP_PITCH
      position: -0.356
      gain: 50
    - id: L_SHOULDER_ROLL
      position: 0.144038
      gain: 20
  duration: 800