- duration: 2000
  targets:
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_PITCH
      position: -0.35
      gain: 50
    - id: R_HIP_PITCH
      position: -0.35
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 50
- targets:
    - gain: 30
      id: L_HIP_YAW
      position: 0
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.27
      gain: 30
    - id: R_HIP_ROLL
      position: 0.27
      gain: 50
    - id: L_HIP_PITCH
      position: -0.45
      gain: 30
    - id: R_HIP_PITCH
      position: -0.45
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.27
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.27
      gain: 50
  duration: 800
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.8
      gain: 30
    - id: R_HIP_PITCH
      position: -0.45
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 300
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.86
      gain: 30
    - id: R_HIP_PITCH
      position: -0.15
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: 0.5
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 100
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.6
      gain: 30
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 400
- duration: 750
  targets:
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_YAW
      position: 0.021481
      gain: 50
    - id: L_HIP_ROLL
      position: 0.398566
      gain: 30
    - id: R_HIP_ROLL
      position: 0.202535
      gain: 50
    - id: L_HIP_PITCH
      position: -0.52068
      gain: 30
    - id: R_HIP_PITCH
      position: -0.431688
      gain: 50
    - id: L_KNEE
      position: 0.774849
      gain: 30
    - id: R_KNEE
      position: 0.569246
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.498665
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.328352
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.308405
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.302268
      gain: 50
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_PITCH
      position: -0.45
      gain: 50
    - id: R_HIP_PITCH
      position: -0.45
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 50
  duration: 550
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 50
  duration: 500