- duration: 2000
  targets:
    - gain: 50
      id: L_HIP_YAW
      position: -0
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: -0
      gain: 50
    - id: R_HIP_ROLL
      position: -0
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0
      gain: 50
    - id: R_ANKLE_ROLL
      position: -0
      gain: 50
- targets:
    - gain: 30
      id: L_HIP_YAW
      position: -0
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.27
      gain: 30
    - id: R_HIP_ROLL
      position: 0.27
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 30
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.27
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.27
      gain: 50
  duration: 800
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 20
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 20
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.6
      gain: 20
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 20
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 20
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 300
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 20
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 20
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 20
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.7
      gain: 20
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 20
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.3789858
      gain: 80
  duration: 180
- duration: 50
  targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.02000004
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 80
    - id: L_HIP_PITCH
      position: -1.193728
      gain: 80
    - id: L_KNEE
      position: 0.1104736
      gain: 80
    - id: L_ANKLE_PITCH
      position: 0.3068711
      gain: 80
- duration: 400
  targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -1.1
      gain: 30
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.01999997
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 80
- duration: 300
  targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - gain: 30
      id: L_HIP_PITCH
      position: -1.1
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.32
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.52
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.8
      gain: 30
    - id: R_HIP_PITCH
      position: -0.45
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.42
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 400
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 50
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: -0
      gain: 50
    - id: R_HIP_ROLL
      position: -0
      gain: 50
    - id: L_HIP_PITCH
      position: -0.35
      gain: 50
    - id: R_HIP_PITCH
      position: -0.35
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0
      gain: 50
    - id: R_ANKLE_ROLL
      position: -0
      gain: 50
  duration: 750