- targets:
    - gain: 50
      id: L_HIP_YAW
      position: -0
    - position: -0
      gain: 50
      id: R_HIP_YAW
    - gain: 50
      position: -0
      id: L_HIP_ROLL
    - gain: 50
      position: -0
      id: R_HIP_ROLL
    - position: -0.25
      id: L_HIP_PITCH
      gain: 50
    - gain: 50
      position: -0.25
      id: R_HIP_PITCH
    - gain: 50
      id: L_KNEE
      position: 0.5
    - id: R_KNEE
      gain: 50
      position: 0.5
    - id: L_ANKLE_PITCH
      gain: 50
      position: -0.25
    - id: R_ANKLE_PITCH
      gain: 50
      position: -0.25
    - id: L_ANKLE_ROLL
      position: -0
      gain: 50
    - position: -0
      gain: 50
      id: R_ANKLE_ROLL
  duration: 2000
- duration: 800
  targets:
    - position: -0
      id: L_HIP_YAW
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - position: 0.27
      gain: 30
      id: L_HIP_ROLL
    - id: R_HIP_ROLL
      position: 0.27
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 30
    - position: -0.25
      gain: 50
      id: R_HIP_PITCH
    - id: L_KNEE
      position: 0.5
      gain: 30
    - gain: 50
      id: R_KNEE
      position: 0.5
    - position: -0.25
      id: L_ANKLE_PITCH
      gain: 30
    - position: -0.25
      id: R_ANKLE_PITCH
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.27
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.27
      gain: 50
- duration: 300
  targets:
    - position: -0
      gain: 30
      id: L_HIP_YAW
    - position: -0
      gain: 50
      id: R_HIP_YAW
    - id: L_HIP_ROLL
      gain: 30
      position: 0.42
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - position: -0.6
      gain: 30
      id: L_HIP_PITCH
    - id: R_HIP_PITCH
      gain: 50
      position: -0.25
    - position: 1.4
      gain: 30
      id: L_KNEE
    - position: 0.5
      gain: 50
      id: R_KNEE
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 30
    - gain: 50
      id: R_ANKLE_PITCH
      position: -0.25
    - position: -0.42
      gain: 30
      id: L_ANKLE_ROLL
    - position: -0.32
      id: R_ANKLE_ROLL
      gain: 50
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - position: -0
      gain: 50
      id: R_HIP_YAW
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - gain: 50
      id: R_HIP_ROLL
      position: 0.32
    - position: -0.6
      id: L_HIP_PITCH
      gain: 30
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 1.4
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.7
      gain: 30
    - position: -0.25
      id: R_ANKLE_PITCH
      gain: 50
    - gain: 30
      id: L_ANKLE_ROLL
      position: -0.42
    - position: -0.32
      gain: 50
      id: R_ANKLE_ROLL
  duration: 180
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - position: -0
      gain: 50
      id: R_HIP_YAW
    - gain: 50
      id: R_HIP_ROLL
      position: 0.32
    - id: L_HIP_PITCH
      position: -1.1
      gain: 30
    - position: -0.25
      gain: 50
      id: R_HIP_PITCH
    - id: L_KNEE
      position: 0.5
      gain: 30
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: 0.56
      gain: 30
    - position: -0.25
      gain: 50
      id: R_ANKLE_PITCH
    - id: L_ANKLE_ROLL
      position: -0.02000004
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
    - id: L_HIP_ROLL
      position: 0.8239489
      gain: 30
  duration: 200
- duration: 200
  targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - position: -0
      gain: 50
      id: R_HIP_YAW
    - id: L_HIP_ROLL
      position: 0.824
      gain: 30
    - position: 0.32
      gain: 50
      id: R_HIP_ROLL
    - id: L_HIP_PITCH
      position: -1.1
      gain: 30
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 30
    - position: 0.5
      gain: 50
      id: R_KNEE
    - id: L_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - gain: 30
      id: L_ANKLE_ROLL
      position: -0.01999997
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
- targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: -0.17
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - position: -1
      gain: 30
      id: L_HIP_PITCH
    - position: -0.25
      gain: 50
      id: R_HIP_PITCH
    - id: L_KNEE
      position: 0.5
      gain: 30
    - gain: 50
      id: R_KNEE
      position: 0.5
    - id: L_ANKLE_PITCH
      position: 0.36
      gain: 30
    - position: -0.25
      gain: 50
      id: R_ANKLE_PITCH
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.02
      gain: 30
  duration: 85
- duration: 1000
  targets:
    - gain: 30
      id: L_HIP_YAW
      position: -0
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: -0.17
      gain: 30
    - position: 0.32
      gain: 50
      id: R_HIP_ROLL
    - id: L_HIP_PITCH
      position: -1
      gain: 30
    - position: -0.25
      gain: 50
      id: R_HIP_PITCH
    - id: L_KNEE
      position: 0.5
      gain: 30
    - position: 0.5
      gain: 50
      id: R_KNEE
    - position: 0.36
      gain: 30
      id: L_ANKLE_PITCH
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - position: -0.02
      gain: 30
      id: L_ANKLE_ROLL
    - position: -0.32
      gain: 50
      id: R_ANKLE_ROLL
- targets:
    - position: -0
      gain: 30
      id: L_HIP_YAW
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: 0.42
      gain: 30
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - position: -1.1
      gain: 30
      id: L_HIP_PITCH
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      gain: 30
      position: 0.5
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.32
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
  duration: 170
- duration: 400
  targets:
    - gain: 30
      id: L_HIP_YAW
      position: -0
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - position: 0.52
      gain: 30
      id: L_HIP_ROLL
    - id: R_HIP_ROLL
      position: 0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.8
      gain: 30
    - id: R_HIP_PITCH
      position: -0.45
      gain: 50
    - gain: 30
      id: L_KNEE
      position: 1.4
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.8
      gain: 30
    - position: -0.25
      gain: 50
      id: R_ANKLE_PITCH
    - position: -0.42
      gain: 30
      id: L_ANKLE_ROLL
    - id: R_ANKLE_ROLL
      position: -0.32
      gain: 50
- duration: 750
  targets:
    - id: L_HIP_YAW
      position: -0
      gain: 30
    - id: R_HIP_YAW
      position: -0
      gain: 40
    - id: L_HIP_ROLL
      position: -0
      gain: 30
    - id: R_HIP_ROLL
      position: -0
      gain: 40
    - id: L_HIP_PITCH
      position: -0.35
      gain: 30
    - id: R_HIP_PITCH
      position: -0.35
      gain: 40
    - id: L_KNEE
      position: 0.5
      gain: 30
    - position: 0.5
      gain: 40
      id: R_KNEE
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 40
    - gain: 30
      id: L_ANKLE_ROLL
      position: -0
    - id: R_ANKLE_ROLL
      position: -0
      gain: 40