- duration: 2000
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.27
      gain: 30
    - id: L_HIP_ROLL
      position: -0.27
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.27
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.27
      gain: 50
  duration: 800
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.6
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 300
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.6
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.7
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 180
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1.1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.02000004
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_HIP_ROLL
      position: -0.8239489
      gain: 30
    - id: R_KNEE
      position: 0.8515673
      gain: 30
  duration: 200
- duration: 200
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.824
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1.1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.852
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.01999997
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.17
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.36
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.02
      gain: 30
    - id: R_KNEE
      position: 0.5891925
      gain: 30
  duration: 100
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.17
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.589
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.36
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.02
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 1000
- duration: 170
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1.1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.32
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
- duration: 400
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.52
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.8
      gain: 30
    - id: L_HIP_PITCH
      position: -0.45
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 40
    - id: R_HIP_ROLL
      position: 0
      gain: 30
    - id: L_HIP_ROLL
      position: 0
      gain: 40
    - id: R_HIP_PITCH
      position: -0.35
      gain: 30
    - id: L_HIP_PITCH
      position: -0.35
      gain: 40
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 40
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 40
    - id: R_ANKLE_ROLL
      position: 0
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0
      gain: 40
  duration: 750