- duration: 1000
  targets:
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: R_HIP_PITCH
      position: -0.35
      gain: 50
    - id: L_HIP_PITCH
      position: -0.35
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: -0
      gain: 50
    - id: L_HIP_YAW
      position: -0
      gain: 50
    - id: R_HIP_YAW
      position: -0
      gain: 50
    - id: L_HIP_ROLL
      position: -0
      gain: 50
    - id: R_HIP_ROLL
      position: -0
      gain: 50
- duration: 1000
  targets:
    - id: R_HIP_YAW
      position: -0
      gain: 30
    - id: L_HIP_ROLL
      position: -0.27
      gain: 50
    - id: R_HIP_ROLL
      position: -0.27
      gain: 30
    - id: L_HIP_PITCH
      position: -0.45
      gain: 50
    - id: R_HIP_PITCH
      position: -0.45
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.27
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.27
      gain: 30
    - id: L_HIP_YAW
      position: -0
      gain: 50
- duration: 1000
  targets:
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_HIP_PITCH
      position: -0.8
      gain: 30
    - id: L_HIP_PITCH
      position: -0.45
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_YAW
      position: -0
      gain: 30
    - id: L_HIP_YAW
      position: -0
      gain: 50
- duration: 1500
  targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.004603
      gain: 30
    - id: R_KNEE
      position: 1.341027
      gain: 30
    - id: R_HIP_PITCH
      position: -0.885323
      gain: 30
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: R_HIP_ROLL
      position: -0.217878
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.018412
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.28539
      gain: 50
    - id: L_HIP_PITCH
      position: -0.721147
      gain: 50
- targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: R_HIP_ROLL
      position: -0.217878
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.018412
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.28539
      gain: 50
    - id: R_HIP_PITCH
      position: -1.508271
      gain: 50
    - id: R_KNEE
      position: 0.613742
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.328352
      gain: 30
    - id: L_HIP_PITCH
      position: -0.497
      gain: 50
  duration: 200
- targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_HIP_PITCH
      position: -0.885323
      gain: 30
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: R_HIP_ROLL
      position: -0.217878
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_HIP_PITCH
      position: -0.395864
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.280787
      gain: 50
    - id: R_KNEE
      position: 0.243963
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.382054
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.039893
      gain: 30
  duration: 400
- duration: 700
  targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_HIP_PITCH
      position: -0.885323
      gain: 30
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: R_HIP_ROLL
      position: -0.217878
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.018412
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_HIP_PITCH
      position: -0.395864
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.280787
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.105871
      gain: 30
    - id: R_KNEE
      position: 0.998865
      gain: 30
- targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_HIP_PITCH
      position: -0.885323
      gain: 30
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: R_HIP_ROLL
      position: -0.217878
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.018412
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_HIP_PITCH
      position: -0.395864
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.273115
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.098199
      gain: 30
    - id: R_KNEE
      position: 1.195263
      gain: 30
  duration: 300
- targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: L_HIP_YAW
      position: 0.030687
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_HIP_ROLL
      position: -0.141161
      gain: 50
    - id: R_HIP_YAW
      position: -0.019947
      gain: 30
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: L_HIP_PITCH
      position: -0.395864
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.273115
      gain: 50
    - id: R_HIP_ROLL
      position: -0.210207
      gain: 30
    - id: R_HIP_PITCH
      position: -0.421948
      gain: 30
    - id: R_KNEE
      position: 0.575383
      gain: 30
    - id: R_ANKLE_PITCH
      position: -0.173382
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.2501
      gain: 30
  duration: 500
- duration: 1000
  targets:
    - id: L_ANKLE_PITCH
      position: -0.194863
      gain: 50
    - id: R_ELBOW
      position: -1.389742
      gain: 20
    - id: L_ELBOW
      position: -1.144246
      gain: 20
    - id: R_SHOULDER_ROLL
      position: -0.524558
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.619688
      gain: 20
    - id: R_SHOULDER_PITCH
      position: 1.633705
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 1.65672
      gain: 20
    - id: L_KNEE
      position: 0.512475
      gain: 50
    - id: R_KNEE
      position: 0.575383
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.173382
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.029153
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.015344
      gain: 50
    - id: R_HIP_ROLL
      position: -0.003069
      gain: 50
    - id: L_HIP_ROLL
      position: 0.02455
      gain: 50
    - id: L_HIP_YAW
      position: 0.075183
      gain: 50
    - id: R_HIP_YAW
      position: 0.05984
      gain: 50
    - id: R_HIP_PITCH
      position: -0.469513
      gain: 50
    - id: L_HIP_PITCH
      position: -0.409673
      gain: 50