- targets:
    - position: 0
      gain: 50
      id: R_HIP_YAW
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50
  duration: 2000
- targets:
    - gain: 30
      id: R_HIP_YAW
      position: 0
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.27
      gain: 30
    - id: L_HIP_ROLL
      position: -0.27
      gain: 50
    - id: R_HIP_PITCH
      position: -0.25
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.27
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.27
      gain: 50
    - id: R_SHOULDER_ROLL
      position: -0.7270927
      gain: 80
    - id: R_SHOULDER_PITCH
      position: 1.748782
      gain: 80
  duration: 800
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.6
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 300
- duration: 180
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.6
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.7
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
- targets:
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.01999997
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_KNEE
      position: 0.2025349
      gain: 80
    - id: R_HIP_YAW
      position: -0.4633753
      gain: 80
    - id: R_HIP_ROLL
      position: -0.5078716
      gain: 80
    - id: R_HIP_PITCH
      position: -1.10627
      gain: 80
  duration: 200
- duration: 85
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.17
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.02
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.2869245
      gain: 80
    - id: R_KNEE
      position: 0.4526348
      gain: 80
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0.17
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.02
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.2869245
      gain: 80
    - id: R_KNEE
      position: 0.4526348
      gain: 80
  duration: 1000
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.42
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -1.1
      gain: 30
    - id: L_HIP_PITCH
      position: -0.25
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: 0.56
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.32
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 170
- targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: -0.52
      gain: 30
    - id: L_HIP_ROLL
      position: -0.32
      gain: 50
    - id: R_HIP_PITCH
      position: -0.8
      gain: 30
    - id: L_HIP_PITCH
      position: -0.45
      gain: 50
    - id: R_KNEE
      position: 1.4
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.8
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0.42
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.32
      gain: 50
  duration: 400
- duration: 750
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 30
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_PITCH
      position: -0.35
      gain: 30
    - id: L_HIP_PITCH
      position: -0.35
      gain: 50
    - id: R_KNEE
      position: 0.5
      gain: 30
    - id: L_KNEE
      position: 0.5
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.25
      gain: 30
    - id: L_ANKLE_PITCH
      position: -0.25
      gain: 50
    - id: R_ANKLE_ROLL
      position: 0
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0
      gain: 50