- duration: 500
  targets:
    - position: 2.15269
      gain: 30
      id: R_SHOULDER_PITCH
    - gain: 30
      id: L_SHOULDER_PITCH
      position: 2.15269
    - id: R_SHOULDER_ROLL
      position: -0.199418
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.199418
      gain: 30
    - id: R_ELBOW
      position: -0.802783
      gain: 30
    - id: L_ELBOW
      position: -0.802783
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_ROLL
      position: 0
      gain: 30
    - id: L_HIP_ROLL
      gain: 30
      position: 0
    - id: R_HIP_PITCH
      position: -1.09424
      gain: 30
    - id: L_HIP_PITCH
      position: -1.08913
      gain: 30
    - gain: 30
      id: R_KNEE
      position: 1.66181
    - gain: 30
      id: L_KNEE
      position: 1.69249
    - id: R_ANKLE_PITCH
      gain: 30
      position: -0.792557
    - id: L_ANKLE_PITCH
      position: -0.736311
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.092039
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.097152
      gain: 30
- targets:
    - gain: 30
      id: R_SHOULDER_PITCH
      position: 3.79916
    - gain: 30
      id: L_SHOULDER_PITCH
      position: 3.79916
    - id: R_SHOULDER_ROLL
      position: -0.005113
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.005113
      gain: 30
    - id: R_ELBOW
      position: -2.57197
      gain: 30
    - id: L_ELBOW
      position: -2.57197
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_ROLL
      position: 0
      gain: 30
    - id: L_HIP_ROLL
      position: 0
      gain: 30
    - id: R_HIP_PITCH
      position: -0.76699
      gain: 30
    - id: L_HIP_PITCH
      position: -0.787443
      gain: 30
    - id: R_KNEE
      position: 1.59534
      gain: 30
    - id: L_KNEE
      position: 1.61579
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.455081
      gain: 30
    - id: L_ANKLE_PITCH
      position: 0.465308
      gain: 30
    - id: R_ANKLE_ROLL
      position: 0.178964
      gain: 30
    - id: L_ANKLE_ROLL
      position: 0.046019
      gain: 30
  duration: 500
- targets:
    - id: R_SHOULDER_PITCH
      position: 4.0855
      gain: 30
    - id: L_SHOULDER_PITCH
      position: 4.0855
      gain: 30
    - id: R_SHOULDER_ROLL
      position: -0.056246
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.056246
      gain: 30
    - id: R_ELBOW
      position: -1.8101
      gain: 30
    - id: L_ELBOW
      position: -1.8101
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 30
    - id: L_HIP_YAW
      position: 0
      gain: 30
    - id: R_HIP_ROLL
      position: 0
      gain: 30
    - id: L_HIP_ROLL
      position: 0
      gain: 30
    - id: R_HIP_PITCH
      position: -1.2323
      gain: 30
    - id: L_HIP_PITCH
      position: -1.19651
      gain: 30
    - id: R_KNEE
      position: 1.76919
      gain: 30
    - id: L_KNEE
      position: 1.77942
      gain: 30
    - id: R_ANKLE_PITCH
      position: 0.453722
      gain: 30
    - id: L_ANKLE_PITCH
      position: 0.457249
      gain: 30
    - id: R_ANKLE_ROLL
      position: -0.035793
      gain: 30
    - id: L_ANKLE_ROLL
      position: -0.010227
      gain: 30
  duration: 500
- targets:
    - id: R_SHOULDER_PITCH
      position: 3.3901
      gain: 30
    - id: L_SHOULDER_PITCH
      position: 3.3901
      gain: 30
    - id: R_SHOULDER_ROLL
      position: -0.01534
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.01534
      gain: 30
    - id: R_ELBOW
      position: -0.480647
      gain: 30
    - id: L_ELBOW
      position: -0.480647
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - id: L_HIP_YAW
      position: 0
      gain: 50
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - id: R_HIP_PITCH
      position: 0.046019
      gain: 50
    - id: L_HIP_PITCH
      position: 0.143172
      gain: 50
    - id: R_KNEE
      position: 1.52887
      gain: 50
    - id: L_KNEE
      position: 1.4266
      gain: 50
    - id: R_ANKLE_PITCH
      position: -0.291456
      gain: 50
    - id: L_ANKLE_PITCH
      position: -0.29657
      gain: 50
    - id: R_ANKLE_ROLL
      position: -0.025566
      gain: 50
    - id: L_ANKLE_ROLL
      position: -0.102265
      gain: 50
  duration: 500
- targets:
    - id: R_SHOULDER_PITCH
      position: 2.689341
      gain: 30
    - id: L_SHOULDER_PITCH
      position: 2.709288
      gain: 30
    - id: R_SHOULDER_ROLL
      position: -0.053511
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.056579
      gain: 30
    - id: R_ELBOW
      position: 0.04488
      gain: 30
    - id: L_ELBOW
      position: 0.029536
      gain: 30
    - id: R_HIP_YAW
      position: -0.018412
      gain: 60
    - id: L_HIP_YAW
      position: 0.023015
      gain: 60
    - id: R_HIP_ROLL
      position: -0.016878
      gain: 60
    - id: L_HIP_ROLL
      position: -0.026084
      gain: 60
    - id: R_HIP_PITCH
      position: 0.291528
      gain: 60
    - id: L_HIP_PITCH
      position: 0.291528
      gain: 60
    - id: R_KNEE
      position: 1.92715
      gain: 60
    - id: L_KNEE
      position: 1.919479
      gain: 60
    - id: R_ANKLE_PITCH
      position: -1.232087
      gain: 60
    - id: L_ANKLE_PITCH
      position: -1.219813
      gain: 60
    - id: R_ANKLE_ROLL
      position: -0.009206
      gain: 60
    - id: L_ANKLE_ROLL
      position: 0.023015
      gain: 60
  duration: 500
- duration: 600
  targets:
    - id: R_SHOULDER_PITCH
      position: 2.43392
      gain: 30
    - gain: 30
      id: L_SHOULDER_PITCH
      position: 2.433056
    - id: R_SHOULDER_ROLL
      position: -0.138058
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.138058
      gain: 30
    - id: R_ELBOW
      position: -0.465308
      gain: 30
    - id: L_ELBOW
      position: -0.465308
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 60
    - id: L_HIP_YAW
      position: 0
      gain: 60
    - id: R_HIP_ROLL
      position: 0
      gain: 60
    - id: L_HIP_ROLL
      position: 0
      gain: 60
    - id: R_HIP_PITCH
      position: 0.51644
      gain: 60
    - id: L_HIP_PITCH
      position: 0.51644
      gain: 60
    - id: R_KNEE
      position: 1.7585
      gain: 60
    - id: L_KNEE
      position: 1.75521
      gain: 60
    - id: R_ANKLE_PITCH
      position: -1.28854
      gain: 60
    - id: L_ANKLE_PITCH
      position: -1.37547
      gain: 60
    - id: R_ANKLE_ROLL
      position: -0.010227
      gain: 60
    - id: L_ANKLE_ROLL
      position: -0.071586
      gain: 60
- targets:
    - id: R_SHOULDER_PITCH
      position: 1.60557
      gain: 30
    - id: L_SHOULDER_PITCH
      position: 1.60557
      gain: 30
    - id: R_SHOULDER_ROLL
      position: -0.138058
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.138058
      gain: 30
    - id: R_ELBOW
      position: -0.639159
      gain: 30
    - id: L_ELBOW
      position: -0.639159
      gain: 30
    - id: R_HIP_YAW
      position: 0
      gain: 60
    - id: L_HIP_YAW
      position: 0
      gain: 60
    - id: R_HIP_ROLL
      position: 0
      gain: 60
    - id: L_HIP_ROLL
      position: 0
      gain: 60
    - id: R_HIP_PITCH
      position: -0.5011
      gain: 60
    - id: L_HIP_PITCH
      position: -0.572686
      gain: 60
    - id: R_KNEE
      position: 1.7
      gain: 60
    - id: L_KNEE
      position: 1.7
      gain: 60
    - id: R_ANKLE_PITCH
      position: -1.00013
      gain: 60
    - id: L_ANKLE_PITCH
      position: -1.00013
      gain: 60
    - id: R_ANKLE_ROLL
      position: 0.035793
      gain: 60
    - id: L_ANKLE_ROLL
      position: -0.061359
      gain: 60
  duration: 500
- duration: 500
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - gain: 50
      id: L_HIP_YAW
      position: 0
    - position: -0.055
      gain: 50
      id: R_HIP_ROLL
    - id: L_HIP_ROLL
      position: 0.055
      gain: 50
    - id: R_HIP_PITCH
      position: -0.77
      gain: 50
    - id: L_HIP_PITCH
      position: -0.77
      gain: 50
    - gain: 50
      id: R_KNEE
      position: 2.08
    - id: L_KNEE
      position: 2.08
      gain: 50
    - gain: 50
      position: -1.31
      id: R_ANKLE_PITCH
    - id: L_ANKLE_PITCH
      position: -1.31
      gain: 50
    - gain: 50
      position: 0.055
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.055
      gain: 50
    - position: -2.5
      id: L_ELBOW
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.42
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 2.469929
      gain: 20
    - position: 2.47
      gain: 20
      id: R_SHOULDER_PITCH
    - id: R_SHOULDER_ROLL
      position: -0.42
      gain: 20
    - id: R_ELBOW
      position: -2.5
      gain: 20