- duration: 700
  targets:
    - id: R_SHOULDER_PITCH
      position: 3.13955
      gain: 30
    - gain: 30
      id: L_SHOULDER_PITCH
      position: 3.13955
    - position: -0.066473
      gain: 30
      id: R_SHOULDER_ROLL
    - id: L_SHOULDER_ROLL
      position: 0.066473
      gain: 30
    - gain: 30
      id: R_ELBOW
      position: -2.6589
    - gain: 30
      id: L_ELBOW
      position: -2.6589
    - gain: 50
      id: R_HIP_YAW
      position: -0.020453
    - gain: 50
      id: L_HIP_YAW
      position: 0.020453
    - id: R_HIP_ROLL
      position: 0
      gain: 50
    - id: L_HIP_ROLL
      position: 0
      gain: 50
    - gain: 50
      id: R_HIP_PITCH
      position: -0.271003
    - position: -0.271003
      gain: 50
      id: L_HIP_PITCH
    - gain: 50
      position: 0.424401
      id: R_KNEE
    - gain: 50
      id: L_KNEE
      position: 0.424401
    - id: R_ANKLE_PITCH
      position: -1.05333
      gain: 50
    - position: -1.05333
      gain: 50
      id: L_ANKLE_PITCH
    - position: 0.01534
      gain: 50
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.01534
      gain: 50
- duration: 500
  targets:
    - id: R_SHOULDER_PITCH
      gain: 30
      position: 0.772104
    - position: 0.772104
      gain: 30
      id: L_SHOULDER_PITCH
    - position: -0.158511
      id: R_SHOULDER_ROLL
      gain: 30
    - id: L_SHOULDER_ROLL
      position: 0.158511
      gain: 30
    - position: -2.71003
      gain: 30
      id: R_ELBOW
    - id: L_ELBOW
      position: -2.71003
      gain: 30
    - id: R_HIP_YAW
      gain: 50
      position: -0.025566
    - gain: 50
      position: 0.025566
      id: L_HIP_YAW
    - position: 0.01534
      id: R_HIP_ROLL
      gain: 50
    - id: L_HIP_ROLL
      gain: 50
      position: -0.01534
    - position: -1.64647
      gain: 50
      id: R_HIP_PITCH
    - id: L_HIP_PITCH
      position: -1.64647
      gain: 50
    - position: 1.03288
      gain: 50
      id: R_KNEE
    - id: L_KNEE
      position: 1.03288
      gain: 50
    - id: R_ANKLE_PITCH
      gain: 50
      position: -1.36524
    - position: -1.36524
      gain: 50
      id: L_ANKLE_PITCH
    - gain: 50
      position: 0.046019
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.046019
      gain: 50
- duration: 800
  targets:
    - id: R_SHOULDER_PITCH
      position: 1.01754
      gain: 30
    - id: L_SHOULDER_PITCH
      position: 1.01754
      gain: 30
    - gain: 30
      id: R_SHOULDER_ROLL
      position: 0.035793
    - id: L_SHOULDER_ROLL
      position: -0.035793
      gain: 30
    - position: -0.25055
      gain: 30
      id: R_ELBOW
    - id: L_ELBOW
      position: -0.25055
      gain: 30
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
    - position: -0.025566
      gain: 50
      id: L_HIP_YAW
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
    - id: L_HIP_ROLL
      gain: 50
      position: 0.025566
    - id: R_HIP_PITCH
      position: -1.69761
      gain: 50
    - id: L_HIP_PITCH
      position: -1.69761
      gain: 50
    - position: 2.27029
      gain: 50
      id: R_KNEE
    - position: 2.27029
      gain: 50
      id: L_KNEE
    - position: -1.16071
      gain: 50
      id: R_ANKLE_PITCH
    - id: L_ANKLE_PITCH
      position: -1.16071
      gain: 50
    - gain: 50
      id: R_ANKLE_ROLL
      position: 0.03068
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
- duration: 700
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 50
    - gain: 50
      id: L_HIP_YAW
      position: 0
    - position: -0.055
      gain: 50
      id: R_HIP_ROLL
    - id: L_HIP_ROLL
      position: 0.055
      gain: 50
    - id: R_HIP_PITCH
      position: -0.77
      gain: 50
    - id: L_HIP_PITCH
      position: -0.77
      gain: 50
    - gain: 50
      id: R_KNEE
      position: 2.08
    - id: L_KNEE
      position: 2.08
      gain: 50
    - gain: 50
      position: -1.31
      id: R_ANKLE_PITCH
    - id: L_ANKLE_PITCH
      position: -1.31
      gain: 50
    - gain: 50
      position: 0.055
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.055
      gain: 50
    - position: -2.5
      id: L_ELBOW
      gain: 20
    - id: L_SHOULDER_ROLL
      position: 0.42
      gain: 20
    - id: L_SHOULDER_PITCH
      position: 2.469929
      gain: 20
    - position: 2.47
      gain: 20
      id: R_SHOULDER_PITCH
    - id: R_SHOULDER_ROLL
      position: -0.42
      gain: 20
    - id: R_ELBOW
      position: -2.5
      gain: 20