- duration: 1000
  targets:
    - gain: 30
      id: L_HIP_YAW
      position: -0.004815704
    - id: L_HIP_ROLL
      position: -0.01112923
      gain: 30
    - position: -1.014017
      gain: 30
      id: L_HIP_PITCH
    - gain: 30
      position: 0.9894299
      id: L_KNEE
    - position: -0.3837897
      id: L_ANKLE_PITCH
      gain: 30
    - gain: 30
      position: 0.01212681
      id: L_ANKLE_ROLL
    - gain: 30
      position: 0.004815704
      id: R_HIP_YAW
    - position: 0.01112923
      id: R_HIP_ROLL
      gain: 30
    - gain: 30
      position: -1.014017
      id: R_HIP_PITCH
    - position: 0.9894299
      gain: 30
      id: R_KNEE
    - position: -0.3837897
      gain: 30
      id: R_ANKLE_PITCH
    - gain: 30
      id: R_ANKLE_ROLL
      position: -0.01212681



