
zones:
  forward:
    active_ball_timeout: 10
    zone_return_timeout: 20
    zone: [[x, y], [x, y]]
    start_position: [x,y]
    default_position: [x,y]
    goalie: false

  centre:
    active_ball_timeout: 10
    zone_return_timeout: 20
    zone: [[x, y], [x, y]]
    start_position: [x,y]
    default_position: [x,y]
    goalie: false

  guard:
    active_ball_timeout: 10
    zone_return_timeout: 20
    zone: [[x, y], [x, y]]
    start_position: [x,y]
    default_position: [x,y]
    goalie: false

  goalie:
    active_ball_timeout: 10
    zone_return_timeout: 20
    zone: [[x, y], [x, y]]
    start_position: [x,y]
    default_position: [x,y]
    goalie: true
