MAX_BALL_DISTANCE: 0.25 
KICK_DISTANCE_THRESHOLD: 0.15
BALL_CERTAINTY_THRESHOLD: 0.5
BALL_SELF_INTERSECTION_REGION: 1.0
BALL_LOOK_ERROR: [0.1, 0.1]
BALL_MOVEMENT_THRESHOLD: 0.1
GOALIE: 0
START_POSITION: [0, 0]
MY_ZONE: 1
ZONE_1_DEFAULT: [0, 0]
ZONE_1:
  - [0,1]
  - [0,1]
ZONE_2_DEFAULT: [0, 0]
ZONE_2:
  - [0,1]
  - [0,1]
ZONE_3_DEFAULT: [0, 0]
ZONE_3:
  - [0,1]
  - [0,1]
ZONE_4_DEFAULT: [0, 0]
ZONE_4:
  - [0,1]
  - [0,1]
