SimulateVision: true
SimulateGoalObservations: true
SimulateBallObservations: true
SimulateOdometry: false
SimulateRobotMovement: true
SimulateBallMovement: true
EmitRobotFieldobjects: true
EmitBallFieldobjects: true
