SimulateVision: true
SimulateGoalObservations: true
SimulateBallObservations: true
SimulateOdometry: false
SimulateRobotMovement: true
SimulateRobotWalking: false
RobotMovementPathPeriod: 100
SimulateBallMovement: true
EmitRobotFieldobjects: true
EmitBallFieldobjects: true
RobotImuDriftPeriod: 300
