SimulateVision: true
SimulateGoalObservations: true
SimulateBallObservations: true
SimulateOdometry: true
SimulateRobotMovement: true
SimulateBallMovement: true
EmitRobotFieldobjects: true
EmitBallFieldobjects: true
