{
	"RANDOMIZE" : true,
	"RANDOM_ITERATIONS" : 100,
	"ERROR_THRESHOLD" : 1e-6,
	"xAngle": 0.0,
    "yAngle": 0.0,
    "zAngle": 0.0,
    "x": 0.1,
    "y": 0.1,
    "z": -0.1,
    "left": true,
    "right": true
}