MINIMUM_POINTS: 6
MAX_ITERATIONS_PER_FITTING: 100
CONSENSUS_THRESHOLD: 5.0
MAX_FITTING_ATTEMPTS: 3
ANGLE_MARGIN: 0.25
SELECTION_METHOD: LARGEST_CONSENSUS
RANSAC_MATCHING_TOLERANCE:0.2
MIN_GOAL_SEPARATION: 40
GOAL_HEIGHT_TO_WIDTH_RATIO_MIN: 1.5
THROWOUT_SHORT_GOALS: true
THROWOUT_NARROW_GOALS: true
THROWOUT_ON_ABOVE_KIN_HOR_GOALS: false
THROWOUT_DISTANT_GOALS: true
MAX_GOAL_DISTANCE: 6
MIN_GOAL_HEIGHT: 20
MIN_GOAL_WIDTH: 5
GOAL_WIDTH: 0.10
GOAL_DISTANCE_METHOD: ADAPTIVE
EDGE_OF_SCREEN_MARGIN: 5
D2P_ADAPTIVE_THRESHOLD : 1.0
