ransac:
  minimum_points_for_consensus: 6
  maximum_iterations_per_fitting: 30
  maximum_fitted_models: 3
  consensus_error_threshold: 5.5
aspect_ratio_range: [ 2, 10 ]
visual_horizon_buffer: 0.1
minimum_goal_horizon_angle: 1.3
maximum_vertical_goal_perspective_angle: 10