visual_horizon:
  spacing: 0.1
  subsampling: 0.04
  horizon_buffer: 0.01
  minimum_segment_size: 0.01
ball:
  intersections: 2
  min_jump: 0.02
goals:
  spacing: 0.04
  subsampling: 0.01
  maximum_vertical_cluster_spacing: 0.08
  vertical_cluster_upper_buffer: 0.04
  vertical_cluster_lower_buffer: 0.04
  vertical_sd_jump: 2
  detector_levels:
    - 2.5