visual_horizon:
  spacing: 0.1
  subsampling: 0.04
  horizon_buffer: 0.01
  minimum_segment_size: 0.01
ball:
  intersections: 2
  min_jump: 0.02
goals:
  spacing: 0.04
  subsampling: 0.01
  detector_levels:
    - 2.5