number_of_samples: 4
getup_cancel_trial_threshold: 5
parameters_and_sigmas:
  bodyHeight: 0.0001
  bodyTilt: 0.0001
  footY: 0.0005
  tStep: 0.0002
  tZmp: 0.0005
  stepHeight: 0.0005
segments:
  -
    curvePeriod: 0
    direction: [1, 0]
    normalisedVelocity: 0
    normalisedAngularVelocity: 0
    duration: 2
  -
    curvePeriod: 0
    direction: [1, 0]
    normalisedVelocity: 1
    normalisedAngularVelocity: 0
    duration: 7
  -
    curvePeriod: 0
    direction: [1, 0]
    normalisedVelocity: 1
    normalisedAngularVelocity: 0.5
    duration: 6
  -
    curvePeriod: 0
    direction: [1, 0]
    normalisedVelocity: 1
    normalisedAngularVelocity: 0
    duration: 7
  -
    curvePeriod: 0
    direction: [1, 0]
    normalisedVelocity: 0
    normalisedAngularVelocity: 0
    duration: 2
